name: blckswan speedrun forge v3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 180
    permissions:
      contents: write

    env:
      BRANCH: lineage-21.0
      TARGET: lineage_arm64-userdebug

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update

          sudo apt-get install -y \
            git repo \
            openjdk-17-jdk \
            ccache \
            zip unzip \
            lz4 bc \
            build-essential \
            flex bison gperf \
            libxml2-utils \
            zlib1g-dev \
            libncurses5-dev \
            libncurses5 \
            libtinfo5 \
            python3

      - name: Setup ccache
        run: |
          echo "USE_CCACHE=1" >> $GITHUB_ENV
          echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV
          echo "CCACHE_MAXSIZE=15G" >> $GITHUB_ENV

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: aosp-${{ runner.os }}-${{ env.BRANCH
