name: AOSP Build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          sudo apt update
          sudo apt install -y repo openjdk-17-jdk git
      - name: Sync
        run: |
          mkdir aosp && cd aosp
          repo init -u https://android.googlesource.com/platform/manifest -b android-14.0.0_r1
          repo sync -c -j$(nproc)
      - name: Build
        run: |
          cd aosp
          source build/envsetup.sh
          lunch aosp_arm64-eng
          make -j$(nproc)

